builders:
  abi_json_builder:
    import: "package:variance_dart/builder.dart"
    builder_factories: ["abiJsonBuilder"]
    build_extensions: { ".abi.json": [".m.dart"] }
    auto_apply: root_package
    build_to: source
    defaults:
      generate_for:
        - lib/src/7579/modules/**.abi.json

targets:
  $default:
    builders:
      web3dart_builders:abi_generator:
        generate_for:
          - "lib/src/abis/*.abi.json"
