// Mocks generated by Mockito 5.4.2 from annotations
// in pks_4337_sdk/test/common/address_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i8;
import 'dart:typed_data' as _i6;

import 'package:ens_dart/ens_dart.dart' as _i3;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pks_4337_sdk/src/common/address.dart' as _i5;
import 'package:web3dart/web3dart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEthereumAddress_0 extends _i1.SmartFake
    implements _i2.EthereumAddress {
  _FakeEthereumAddress_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeployedContract_1 extends _i1.SmartFake
    implements _i2.DeployedContract {
  _FakeDeployedContract_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeb3Client_2 extends _i1.SmartFake implements _i2.Web3Client {
  _FakeWeb3Client_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEns_3 extends _i1.SmartFake implements _i3.Ens {
  _FakeEns_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeABI_4 extends _i1.SmartFake implements _i3.ABI {
  _FakeABI_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePubkey_5 extends _i1.SmartFake implements _i3.Pubkey {
  _FakePubkey_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_6 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_7 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Address].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddress extends _i1.Mock implements _i5.Address {
  MockAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get ens => (super.noSuchMethod(
        Invocation.getter(#ens),
        returnValue: '',
      ) as String);
  @override
  _i6.Uint8List get addressBytes => (super.noSuchMethod(
        Invocation.getter(#addressBytes),
        returnValue: _i6.Uint8List(0),
      ) as _i6.Uint8List);
  @override
  String get hex => (super.noSuchMethod(
        Invocation.getter(#hex),
        returnValue: '',
      ) as String);
  @override
  String get hexNo0x => (super.noSuchMethod(
        Invocation.getter(#hexNo0x),
        returnValue: '',
      ) as String);
  @override
  String get hexEip55 => (super.noSuchMethod(
        Invocation.getter(#hexEip55),
        returnValue: '',
      ) as String);
  @override
  String avatarUrl() => (super.noSuchMethod(
        Invocation.method(
          #avatarUrl,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  String diceAvatar() => (super.noSuchMethod(
        Invocation.method(
          #diceAvatar,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  String formattedAddress({int? length = 6}) => (super.noSuchMethod(
        Invocation.method(
          #formattedAddress,
          [],
          {#length: length},
        ),
        returnValue: '',
      ) as String);
  @override
  _i7.Future<String> getEnsName({String? ethRpc}) => (super.noSuchMethod(
        Invocation.method(
          #getEnsName,
          [],
          {#ethRpc: ethRpc},
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i2.EthereumAddress toEthAddress() => (super.noSuchMethod(
        Invocation.method(
          #toEthAddress,
          [],
        ),
        returnValue: _FakeEthereumAddress_0(
          this,
          Invocation.method(
            #toEthAddress,
            [],
          ),
        ),
      ) as _i2.EthereumAddress);
  @override
  int compareTo(_i2.EthereumAddress? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [Ens].
///
/// See the documentation for Mockito's code generation for more information.
class MockEns extends _i1.Mock implements _i3.Ens {
  MockEns() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeployedContract get self => (super.noSuchMethod(
        Invocation.getter(#self),
        returnValue: _FakeDeployedContract_1(
          this,
          Invocation.getter(#self),
        ),
      ) as _i2.DeployedContract);
  @override
  _i2.Web3Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeWeb3Client_2(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Web3Client);
  @override
  _i3.Ens withName(String? _name) => (super.noSuchMethod(
        Invocation.method(
          #withName,
          [_name],
        ),
        returnValue: _FakeEns_3(
          this,
          Invocation.method(
            #withName,
            [_name],
          ),
        ),
      ) as _i3.Ens);
  @override
  void setEnsTextRecord(_i3.EnsTextRecord? _) => super.noSuchMethod(
        Invocation.method(
          #setEnsTextRecord,
          [_],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Ens reverseEns(_i2.EthereumAddress? addr) => (super.noSuchMethod(
        Invocation.method(
          #reverseEns,
          [addr],
        ),
        returnValue: _FakeEns_3(
          this,
          Invocation.method(
            #reverseEns,
            [addr],
          ),
        ),
      ) as _i3.Ens);
  @override
  _i3.Ens withAddress(Object? _) => (super.noSuchMethod(
        Invocation.method(
          #withAddress,
          [_],
        ),
        returnValue: _FakeEns_3(
          this,
          Invocation.method(
            #withAddress,
            [_],
          ),
        ),
      ) as _i3.Ens);
  @override
  _i7.Future<_i3.ABI> abi(
    _i6.Uint8List? node,
    BigInt? contentTypes, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #abi,
          [
            node,
            contentTypes,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<_i3.ABI>.value(_FakeABI_4(
          this,
          Invocation.method(
            #abi,
            [
              node,
              contentTypes,
            ],
            {#atBlock: atBlock},
          ),
        )),
      ) as _i7.Future<_i3.ABI>);
  @override
  _i7.Future<_i2.EthereumAddress> addr(
    _i6.Uint8List? node, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addr,
          [node],
          {#atBlock: atBlock},
        ),
        returnValue:
            _i7.Future<_i2.EthereumAddress>.value(_FakeEthereumAddress_0(
          this,
          Invocation.method(
            #addr,
            [node],
            {#atBlock: atBlock},
          ),
        )),
      ) as _i7.Future<_i2.EthereumAddress>);
  @override
  _i7.Future<_i6.Uint8List> addr$2(
    _i6.Uint8List? node,
    BigInt? coinType, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addr$2,
          [
            node,
            coinType,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i7.Future<_i6.Uint8List>);
  @override
  _i7.Future<bool> authorisations(
    _i6.Uint8List? $param5,
    _i2.EthereumAddress? $param6,
    _i2.EthereumAddress? $param7, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorisations,
          [
            $param5,
            $param6,
            $param7,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
  @override
  _i7.Future<String> clearDNSZone(
    _i6.Uint8List? node, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearDNSZone,
          [node],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<_i6.Uint8List> contenthash(
    _i6.Uint8List? node, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #contenthash,
          [node],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i7.Future<_i6.Uint8List>);
  @override
  _i7.Future<_i6.Uint8List> dnsRecord(
    _i6.Uint8List? node,
    _i6.Uint8List? name,
    BigInt? resource, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dnsRecord,
          [
            node,
            name,
            resource,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i7.Future<_i6.Uint8List>);
  @override
  _i7.Future<bool> hasDNSRecords(
    _i6.Uint8List? node,
    _i6.Uint8List? name, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasDNSRecords,
          [
            node,
            name,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
  @override
  _i7.Future<_i2.EthereumAddress> interfaceImplementer(
    _i6.Uint8List? node,
    _i6.Uint8List? interfaceID, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #interfaceImplementer,
          [
            node,
            interfaceID,
          ],
          {#atBlock: atBlock},
        ),
        returnValue:
            _i7.Future<_i2.EthereumAddress>.value(_FakeEthereumAddress_0(
          this,
          Invocation.method(
            #interfaceImplementer,
            [
              node,
              interfaceID,
            ],
            {#atBlock: atBlock},
          ),
        )),
      ) as _i7.Future<_i2.EthereumAddress>);
  @override
  _i7.Future<String> name(
    _i6.Uint8List? node, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #name,
          [node],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<_i3.Pubkey> pubkey(
    _i6.Uint8List? node, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pubkey,
          [node],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<_i3.Pubkey>.value(_FakePubkey_5(
          this,
          Invocation.method(
            #pubkey,
            [node],
            {#atBlock: atBlock},
          ),
        )),
      ) as _i7.Future<_i3.Pubkey>);
  @override
  _i7.Future<String> setABI(
    _i6.Uint8List? node,
    BigInt? contentType,
    _i6.Uint8List? data, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setABI,
          [
            node,
            contentType,
            data,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> setAddr(
    _i6.Uint8List? node,
    BigInt? coinType,
    _i6.Uint8List? a, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAddr,
          [
            node,
            coinType,
            a,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> setAddr$2(
    _i6.Uint8List? node,
    _i2.EthereumAddress? a, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAddr$2,
          [
            node,
            a,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> setAuthorisation(
    _i6.Uint8List? node,
    _i2.EthereumAddress? target,
    bool? isAuthorised, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAuthorisation,
          [
            node,
            target,
            isAuthorised,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> setContenthash(
    _i6.Uint8List? node,
    _i6.Uint8List? hash, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setContenthash,
          [
            node,
            hash,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> setDNSRecords(
    _i6.Uint8List? node,
    _i6.Uint8List? data, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDNSRecords,
          [
            node,
            data,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> setInterface(
    _i6.Uint8List? node,
    _i6.Uint8List? interfaceID,
    _i2.EthereumAddress? implementer, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInterface,
          [
            node,
            interfaceID,
            implementer,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> setName(
    _i6.Uint8List? node,
    String? name, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setName,
          [
            node,
            name,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> setPubkey(
    _i6.Uint8List? node,
    _i6.Uint8List? x,
    _i6.Uint8List? y, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPubkey,
          [
            node,
            x,
            y,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> setText(
    _i6.Uint8List? node,
    String? key,
    String? value, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setText,
          [
            node,
            key,
            value,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<bool> supportsInterface(
    _i6.Uint8List? interfaceID, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #supportsInterface,
          [interfaceID],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
  @override
  _i7.Future<String> text(
    _i6.Uint8List? node,
    String? key, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #text,
          [
            node,
            key,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Stream<_i3.ABIChanged> aBIChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #aBIChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.ABIChanged>.empty(),
      ) as _i7.Stream<_i3.ABIChanged>);
  @override
  _i7.Stream<_i3.AddrChanged> addrChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addrChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.AddrChanged>.empty(),
      ) as _i7.Stream<_i3.AddrChanged>);
  @override
  _i7.Stream<_i3.AddressChanged> addressChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addressChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.AddressChanged>.empty(),
      ) as _i7.Stream<_i3.AddressChanged>);
  @override
  _i7.Stream<_i3.AuthorisationChanged> authorisationChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorisationChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.AuthorisationChanged>.empty(),
      ) as _i7.Stream<_i3.AuthorisationChanged>);
  @override
  _i7.Stream<_i3.ContenthashChanged> contenthashChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #contenthashChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.ContenthashChanged>.empty(),
      ) as _i7.Stream<_i3.ContenthashChanged>);
  @override
  _i7.Stream<_i3.DNSRecordChanged> dNSRecordChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dNSRecordChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.DNSRecordChanged>.empty(),
      ) as _i7.Stream<_i3.DNSRecordChanged>);
  @override
  _i7.Stream<_i3.DNSRecordDeleted> dNSRecordDeletedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dNSRecordDeletedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.DNSRecordDeleted>.empty(),
      ) as _i7.Stream<_i3.DNSRecordDeleted>);
  @override
  _i7.Stream<_i3.DNSZoneCleared> dNSZoneClearedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dNSZoneClearedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.DNSZoneCleared>.empty(),
      ) as _i7.Stream<_i3.DNSZoneCleared>);
  @override
  _i7.Stream<_i3.InterfaceChanged> interfaceChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #interfaceChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.InterfaceChanged>.empty(),
      ) as _i7.Stream<_i3.InterfaceChanged>);
  @override
  _i7.Stream<_i3.NameChanged> nameChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #nameChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.NameChanged>.empty(),
      ) as _i7.Stream<_i3.NameChanged>);
  @override
  _i7.Stream<_i3.PubkeyChanged> pubkeyChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pubkeyChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.PubkeyChanged>.empty(),
      ) as _i7.Stream<_i3.PubkeyChanged>);
  @override
  _i7.Stream<_i3.TextChanged> textChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #textChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i7.Stream<_i3.TextChanged>.empty(),
      ) as _i7.Stream<_i3.TextChanged>);
  @override
  bool checkSignature(
    _i2.ContractFunction? function,
    String? expected,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkSignature,
          [
            function,
            expected,
          ],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i7.Future<List<dynamic>> read(
    _i2.ContractFunction? function,
    List<dynamic>? params,
    _i2.BlockNum? atBlock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [
            function,
            params,
            atBlock,
          ],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);
  @override
  _i7.Future<String> write(
    _i2.Credentials? credentials,
    _i2.Transaction? base,
    _i2.ContractFunction? function,
    List<dynamic>? parameters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            credentials,
            base,
            function,
            parameters,
          ],
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i4.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i4.Response>);
  @override
  _i7.Future<_i4.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i4.Response>);
  @override
  _i7.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i4.Response>);
  @override
  _i7.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i4.Response>);
  @override
  _i7.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i4.Response>);
  @override
  _i7.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i4.Response>);
  @override
  _i7.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<_i6.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i7.Future<_i6.Uint8List>);
  @override
  _i7.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i7.Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_7(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i7.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
