// Mocks generated by Mockito 5.4.2 from annotations
// in pks_4337_sdk/test/common/address_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i9;
import 'dart:typed_data' as _i6;

import 'package:eip1559/eip1559.dart' as _i8;
import 'package:ens_dart/src/ens_dart.dart' as _i3;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:web3dart/web3dart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeployedContract_0 extends _i1.SmartFake
    implements _i2.DeployedContract {
  _FakeDeployedContract_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeb3Client_1 extends _i1.SmartFake implements _i2.Web3Client {
  _FakeWeb3Client_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEns_2 extends _i1.SmartFake implements _i3.Ens {
  _FakeEns_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeABI_3 extends _i1.SmartFake implements _i3.ABI {
  _FakeABI_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEthereumAddress_4 extends _i1.SmartFake
    implements _i2.EthereumAddress {
  _FakeEthereumAddress_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePubkey_5 extends _i1.SmartFake implements _i3.Pubkey {
  _FakePubkey_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEthPrivateKey_6 extends _i1.SmartFake implements _i2.EthPrivateKey {
  _FakeEthPrivateKey_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncInformation_7 extends _i1.SmartFake
    implements _i2.SyncInformation {
  _FakeSyncInformation_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEtherAmount_8 extends _i1.SmartFake implements _i2.EtherAmount {
  _FakeEtherAmount_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockInformation_9 extends _i1.SmartFake
    implements _i2.BlockInformation {
  _FakeBlockInformation_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_10 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_11 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Ens].
///
/// See the documentation for Mockito's code generation for more information.
class MockEns extends _i1.Mock implements _i3.Ens {
  MockEns() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeployedContract get self => (super.noSuchMethod(
        Invocation.getter(#self),
        returnValue: _FakeDeployedContract_0(
          this,
          Invocation.getter(#self),
        ),
      ) as _i2.DeployedContract);
  @override
  _i2.Web3Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeWeb3Client_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Web3Client);
  @override
  _i3.Ens withName(String? _name) => (super.noSuchMethod(
        Invocation.method(
          #withName,
          [_name],
        ),
        returnValue: _FakeEns_2(
          this,
          Invocation.method(
            #withName,
            [_name],
          ),
        ),
      ) as _i3.Ens);
  @override
  void setEnsTextRecord(_i3.EnsTextRecord? _) => super.noSuchMethod(
        Invocation.method(
          #setEnsTextRecord,
          [_],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Ens reverseEns(_i2.EthereumAddress? addr) => (super.noSuchMethod(
        Invocation.method(
          #reverseEns,
          [addr],
        ),
        returnValue: _FakeEns_2(
          this,
          Invocation.method(
            #reverseEns,
            [addr],
          ),
        ),
      ) as _i3.Ens);
  @override
  _i3.Ens withAddress(Object? _) => (super.noSuchMethod(
        Invocation.method(
          #withAddress,
          [_],
        ),
        returnValue: _FakeEns_2(
          this,
          Invocation.method(
            #withAddress,
            [_],
          ),
        ),
      ) as _i3.Ens);
  @override
  _i5.Future<_i3.ABI> abi(
    _i6.Uint8List? node,
    BigInt? contentTypes, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #abi,
          [
            node,
            contentTypes,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<_i3.ABI>.value(_FakeABI_3(
          this,
          Invocation.method(
            #abi,
            [
              node,
              contentTypes,
            ],
            {#atBlock: atBlock},
          ),
        )),
      ) as _i5.Future<_i3.ABI>);
  @override
  _i5.Future<_i2.EthereumAddress> addr(
    _i6.Uint8List? node, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addr,
          [node],
          {#atBlock: atBlock},
        ),
        returnValue:
            _i5.Future<_i2.EthereumAddress>.value(_FakeEthereumAddress_4(
          this,
          Invocation.method(
            #addr,
            [node],
            {#atBlock: atBlock},
          ),
        )),
      ) as _i5.Future<_i2.EthereumAddress>);
  @override
  _i5.Future<_i6.Uint8List> addr$2(
    _i6.Uint8List? node,
    BigInt? coinType, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addr$2,
          [
            node,
            coinType,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i5.Future<_i6.Uint8List>);
  @override
  _i5.Future<bool> authorisations(
    _i6.Uint8List? $param5,
    _i2.EthereumAddress? $param6,
    _i2.EthereumAddress? $param7, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorisations,
          [
            $param5,
            $param6,
            $param7,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<String> clearDNSZone(
    _i6.Uint8List? node, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearDNSZone,
          [node],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<_i6.Uint8List> contenthash(
    _i6.Uint8List? node, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #contenthash,
          [node],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i5.Future<_i6.Uint8List>);
  @override
  _i5.Future<_i6.Uint8List> dnsRecord(
    _i6.Uint8List? node,
    _i6.Uint8List? name,
    BigInt? resource, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dnsRecord,
          [
            node,
            name,
            resource,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i5.Future<_i6.Uint8List>);
  @override
  _i5.Future<bool> hasDNSRecords(
    _i6.Uint8List? node,
    _i6.Uint8List? name, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasDNSRecords,
          [
            node,
            name,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<_i2.EthereumAddress> interfaceImplementer(
    _i6.Uint8List? node,
    _i6.Uint8List? interfaceID, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #interfaceImplementer,
          [
            node,
            interfaceID,
          ],
          {#atBlock: atBlock},
        ),
        returnValue:
            _i5.Future<_i2.EthereumAddress>.value(_FakeEthereumAddress_4(
          this,
          Invocation.method(
            #interfaceImplementer,
            [
              node,
              interfaceID,
            ],
            {#atBlock: atBlock},
          ),
        )),
      ) as _i5.Future<_i2.EthereumAddress>);
  @override
  _i5.Future<String> name(
    _i6.Uint8List? node, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #name,
          [node],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<_i3.Pubkey> pubkey(
    _i6.Uint8List? node, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pubkey,
          [node],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<_i3.Pubkey>.value(_FakePubkey_5(
          this,
          Invocation.method(
            #pubkey,
            [node],
            {#atBlock: atBlock},
          ),
        )),
      ) as _i5.Future<_i3.Pubkey>);
  @override
  _i5.Future<String> setABI(
    _i6.Uint8List? node,
    BigInt? contentType,
    _i6.Uint8List? data, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setABI,
          [
            node,
            contentType,
            data,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> setAddr(
    _i6.Uint8List? node,
    BigInt? coinType,
    _i6.Uint8List? a, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAddr,
          [
            node,
            coinType,
            a,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> setAddr$2(
    _i6.Uint8List? node,
    _i2.EthereumAddress? a, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAddr$2,
          [
            node,
            a,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> setAuthorisation(
    _i6.Uint8List? node,
    _i2.EthereumAddress? target,
    bool? isAuthorised, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAuthorisation,
          [
            node,
            target,
            isAuthorised,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> setContenthash(
    _i6.Uint8List? node,
    _i6.Uint8List? hash, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setContenthash,
          [
            node,
            hash,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> setDNSRecords(
    _i6.Uint8List? node,
    _i6.Uint8List? data, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDNSRecords,
          [
            node,
            data,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> setInterface(
    _i6.Uint8List? node,
    _i6.Uint8List? interfaceID,
    _i2.EthereumAddress? implementer, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInterface,
          [
            node,
            interfaceID,
            implementer,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> setName(
    _i6.Uint8List? node,
    String? name, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setName,
          [
            node,
            name,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> setPubkey(
    _i6.Uint8List? node,
    _i6.Uint8List? x,
    _i6.Uint8List? y, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPubkey,
          [
            node,
            x,
            y,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> setText(
    _i6.Uint8List? node,
    String? key,
    String? value, {
    required _i2.Credentials? credentials,
    _i2.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setText,
          [
            node,
            key,
            value,
          ],
          {
            #credentials: credentials,
            #transaction: transaction,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<bool> supportsInterface(
    _i6.Uint8List? interfaceID, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #supportsInterface,
          [interfaceID],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<String> text(
    _i6.Uint8List? node,
    String? key, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #text,
          [
            node,
            key,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Stream<_i3.ABIChanged> aBIChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #aBIChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.ABIChanged>.empty(),
      ) as _i5.Stream<_i3.ABIChanged>);
  @override
  _i5.Stream<_i3.AddrChanged> addrChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addrChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.AddrChanged>.empty(),
      ) as _i5.Stream<_i3.AddrChanged>);
  @override
  _i5.Stream<_i3.AddressChanged> addressChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addressChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.AddressChanged>.empty(),
      ) as _i5.Stream<_i3.AddressChanged>);
  @override
  _i5.Stream<_i3.AuthorisationChanged> authorisationChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorisationChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.AuthorisationChanged>.empty(),
      ) as _i5.Stream<_i3.AuthorisationChanged>);
  @override
  _i5.Stream<_i3.ContenthashChanged> contenthashChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #contenthashChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.ContenthashChanged>.empty(),
      ) as _i5.Stream<_i3.ContenthashChanged>);
  @override
  _i5.Stream<_i3.DNSRecordChanged> dNSRecordChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dNSRecordChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.DNSRecordChanged>.empty(),
      ) as _i5.Stream<_i3.DNSRecordChanged>);
  @override
  _i5.Stream<_i3.DNSRecordDeleted> dNSRecordDeletedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dNSRecordDeletedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.DNSRecordDeleted>.empty(),
      ) as _i5.Stream<_i3.DNSRecordDeleted>);
  @override
  _i5.Stream<_i3.DNSZoneCleared> dNSZoneClearedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dNSZoneClearedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.DNSZoneCleared>.empty(),
      ) as _i5.Stream<_i3.DNSZoneCleared>);
  @override
  _i5.Stream<_i3.InterfaceChanged> interfaceChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #interfaceChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.InterfaceChanged>.empty(),
      ) as _i5.Stream<_i3.InterfaceChanged>);
  @override
  _i5.Stream<_i3.NameChanged> nameChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #nameChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.NameChanged>.empty(),
      ) as _i5.Stream<_i3.NameChanged>);
  @override
  _i5.Stream<_i3.PubkeyChanged> pubkeyChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pubkeyChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.PubkeyChanged>.empty(),
      ) as _i5.Stream<_i3.PubkeyChanged>);
  @override
  _i5.Stream<_i3.TextChanged> textChangedEvents({
    _i2.BlockNum? fromBlock,
    _i2.BlockNum? toBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #textChangedEvents,
          [],
          {
            #fromBlock: fromBlock,
            #toBlock: toBlock,
          },
        ),
        returnValue: _i5.Stream<_i3.TextChanged>.empty(),
      ) as _i5.Stream<_i3.TextChanged>);
  @override
  bool checkSignature(
    _i2.ContractFunction? function,
    String? expected,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkSignature,
          [
            function,
            expected,
          ],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<List<dynamic>> read(
    _i2.ContractFunction? function,
    List<dynamic>? params,
    _i2.BlockNum? atBlock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [
            function,
            params,
            atBlock,
          ],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);
  @override
  _i5.Future<String> write(
    _i2.Credentials? credentials,
    _i2.Transaction? base,
    _i2.ContractFunction? function,
    List<dynamic>? parameters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            credentials,
            base,
            function,
            parameters,
          ],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
}

/// A class which mocks [Web3Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeb3Client extends _i1.Mock implements _i2.Web3Client {
  MockWeb3Client() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get printErrors => (super.noSuchMethod(
        Invocation.getter(#printErrors),
        returnValue: false,
      ) as bool);
  @override
  set printErrors(bool? _printErrors) => super.noSuchMethod(
        Invocation.setter(
          #printErrors,
          _printErrors,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i2.EthPrivateKey> credentialsFromPrivateKey(String? privateKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #credentialsFromPrivateKey,
          [privateKey],
        ),
        returnValue: _i5.Future<_i2.EthPrivateKey>.value(_FakeEthPrivateKey_6(
          this,
          Invocation.method(
            #credentialsFromPrivateKey,
            [privateKey],
          ),
        )),
      ) as _i5.Future<_i2.EthPrivateKey>);
  @override
  _i5.Future<String> getClientVersion() => (super.noSuchMethod(
        Invocation.method(
          #getClientVersion,
          [],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<int> getNetworkId() => (super.noSuchMethod(
        Invocation.method(
          #getNetworkId,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
  @override
  _i5.Future<BigInt> getChainId() => (super.noSuchMethod(
        Invocation.method(
          #getChainId,
          [],
        ),
        returnValue: _i5.Future<BigInt>.value(_i7.dummyValue<BigInt>(
          this,
          Invocation.method(
            #getChainId,
            [],
          ),
        )),
      ) as _i5.Future<BigInt>);
  @override
  _i5.Future<bool> isListeningForNetwork() => (super.noSuchMethod(
        Invocation.method(
          #isListeningForNetwork,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<int> getPeerCount() => (super.noSuchMethod(
        Invocation.method(
          #getPeerCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
  @override
  _i5.Future<int> getEtherProtocolVersion() => (super.noSuchMethod(
        Invocation.method(
          #getEtherProtocolVersion,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
  @override
  _i5.Future<_i2.SyncInformation> getSyncStatus() => (super.noSuchMethod(
        Invocation.method(
          #getSyncStatus,
          [],
        ),
        returnValue:
            _i5.Future<_i2.SyncInformation>.value(_FakeSyncInformation_7(
          this,
          Invocation.method(
            #getSyncStatus,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SyncInformation>);
  @override
  _i5.Future<_i2.EthereumAddress> coinbaseAddress() => (super.noSuchMethod(
        Invocation.method(
          #coinbaseAddress,
          [],
        ),
        returnValue:
            _i5.Future<_i2.EthereumAddress>.value(_FakeEthereumAddress_4(
          this,
          Invocation.method(
            #coinbaseAddress,
            [],
          ),
        )),
      ) as _i5.Future<_i2.EthereumAddress>);
  @override
  _i5.Future<bool> isMining() => (super.noSuchMethod(
        Invocation.method(
          #isMining,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<int> getMiningHashrate() => (super.noSuchMethod(
        Invocation.method(
          #getMiningHashrate,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
  @override
  _i5.Future<_i2.EtherAmount> getGasPrice() => (super.noSuchMethod(
        Invocation.method(
          #getGasPrice,
          [],
        ),
        returnValue: _i5.Future<_i2.EtherAmount>.value(_FakeEtherAmount_8(
          this,
          Invocation.method(
            #getGasPrice,
            [],
          ),
        )),
      ) as _i5.Future<_i2.EtherAmount>);
  @override
  _i5.Future<int> getBlockNumber() => (super.noSuchMethod(
        Invocation.method(
          #getBlockNumber,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
  @override
  _i5.Future<_i2.BlockInformation> getBlockInformation({
    String? blockNumber = r'latest',
    bool? isContainFullObj = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBlockInformation,
          [],
          {
            #blockNumber: blockNumber,
            #isContainFullObj: isContainFullObj,
          },
        ),
        returnValue:
            _i5.Future<_i2.BlockInformation>.value(_FakeBlockInformation_9(
          this,
          Invocation.method(
            #getBlockInformation,
            [],
            {
              #blockNumber: blockNumber,
              #isContainFullObj: isContainFullObj,
            },
          ),
        )),
      ) as _i5.Future<_i2.BlockInformation>);
  @override
  _i5.Future<_i2.EtherAmount> getBalance(
    _i2.EthereumAddress? address, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [address],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<_i2.EtherAmount>.value(_FakeEtherAmount_8(
          this,
          Invocation.method(
            #getBalance,
            [address],
            {#atBlock: atBlock},
          ),
        )),
      ) as _i5.Future<_i2.EtherAmount>);
  @override
  _i5.Future<_i6.Uint8List> getStorage(
    _i2.EthereumAddress? address,
    BigInt? position, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStorage,
          [
            address,
            position,
          ],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i5.Future<_i6.Uint8List>);
  @override
  _i5.Future<int> getTransactionCount(
    _i2.EthereumAddress? address, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionCount,
          [address],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
  @override
  _i5.Future<_i2.TransactionInformation?> getTransactionByHash(
          String? transactionHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionByHash,
          [transactionHash],
        ),
        returnValue: _i5.Future<_i2.TransactionInformation?>.value(),
      ) as _i5.Future<_i2.TransactionInformation?>);
  @override
  _i5.Future<_i2.TransactionReceipt?> getTransactionReceipt(String? hash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionReceipt,
          [hash],
        ),
        returnValue: _i5.Future<_i2.TransactionReceipt?>.value(),
      ) as _i5.Future<_i2.TransactionReceipt?>);
  @override
  _i5.Future<_i6.Uint8List> getCode(
    _i2.EthereumAddress? address, {
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCode,
          [address],
          {#atBlock: atBlock},
        ),
        returnValue: _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i5.Future<_i6.Uint8List>);
  @override
  _i5.Future<List<_i2.FilterEvent>> getLogs(_i2.FilterOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogs,
          [options],
        ),
        returnValue:
            _i5.Future<List<_i2.FilterEvent>>.value(<_i2.FilterEvent>[]),
      ) as _i5.Future<List<_i2.FilterEvent>>);
  @override
  _i5.Future<Map<String, dynamic>> getFeeHistory(
    int? blockCount, {
    _i2.BlockNum? atBlock,
    List<double>? rewardPercentiles,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeeHistory,
          [blockCount],
          {
            #atBlock: atBlock,
            #rewardPercentiles: rewardPercentiles,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
  @override
  _i5.Future<String> sendTransaction(
    _i2.Credentials? cred,
    _i2.Transaction? transaction, {
    int? chainId = 1,
    bool? fetchChainIdFromNetworkId = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTransaction,
          [
            cred,
            transaction,
          ],
          {
            #chainId: chainId,
            #fetchChainIdFromNetworkId: fetchChainIdFromNetworkId,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> sendRawTransaction(_i6.Uint8List? signedTransaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRawTransaction,
          [signedTransaction],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<_i6.Uint8List> signTransaction(
    _i2.Credentials? cred,
    _i2.Transaction? transaction, {
    int? chainId = 1,
    bool? fetchChainIdFromNetworkId = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signTransaction,
          [
            cred,
            transaction,
          ],
          {
            #chainId: chainId,
            #fetchChainIdFromNetworkId: fetchChainIdFromNetworkId,
          },
        ),
        returnValue: _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i5.Future<_i6.Uint8List>);
  @override
  _i5.Future<List<dynamic>> call({
    _i2.EthereumAddress? sender,
    required _i2.DeployedContract? contract,
    required _i2.ContractFunction? function,
    required List<dynamic>? params,
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #sender: sender,
            #contract: contract,
            #function: function,
            #params: params,
            #atBlock: atBlock,
          },
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);
  @override
  _i5.Future<BigInt> estimateGas({
    _i2.EthereumAddress? sender,
    _i2.EthereumAddress? to,
    _i2.EtherAmount? value,
    BigInt? amountOfGas,
    _i2.EtherAmount? gasPrice,
    _i2.EtherAmount? maxPriorityFeePerGas,
    _i2.EtherAmount? maxFeePerGas,
    _i6.Uint8List? data,
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateGas,
          [],
          {
            #sender: sender,
            #to: to,
            #value: value,
            #amountOfGas: amountOfGas,
            #gasPrice: gasPrice,
            #maxPriorityFeePerGas: maxPriorityFeePerGas,
            #maxFeePerGas: maxFeePerGas,
            #data: data,
            #atBlock: atBlock,
          },
        ),
        returnValue: _i5.Future<BigInt>.value(_i7.dummyValue<BigInt>(
          this,
          Invocation.method(
            #estimateGas,
            [],
            {
              #sender: sender,
              #to: to,
              #value: value,
              #amountOfGas: amountOfGas,
              #gasPrice: gasPrice,
              #maxPriorityFeePerGas: maxPriorityFeePerGas,
              #maxFeePerGas: maxFeePerGas,
              #data: data,
              #atBlock: atBlock,
            },
          ),
        )),
      ) as _i5.Future<BigInt>);
  @override
  _i5.Future<List<_i8.Fee>> getGasInEIP1559() => (super.noSuchMethod(
        Invocation.method(
          #getGasInEIP1559,
          [],
        ),
        returnValue: _i5.Future<List<_i8.Fee>>.value(<_i8.Fee>[]),
      ) as _i5.Future<List<_i8.Fee>>);
  @override
  _i5.Future<String> callRaw({
    _i2.EthereumAddress? sender,
    required _i2.EthereumAddress? contract,
    required _i6.Uint8List? data,
    _i2.BlockNum? atBlock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callRaw,
          [],
          {
            #sender: sender,
            #contract: contract,
            #data: data,
            #atBlock: atBlock,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Stream<String> addedBlocks() => (super.noSuchMethod(
        Invocation.method(
          #addedBlocks,
          [],
        ),
        returnValue: _i5.Stream<String>.empty(),
      ) as _i5.Stream<String>);
  @override
  _i5.Stream<String> pendingTransactions() => (super.noSuchMethod(
        Invocation.method(
          #pendingTransactions,
          [],
        ),
        returnValue: _i5.Stream<String>.empty(),
      ) as _i5.Stream<String>);
  @override
  _i5.Stream<_i2.FilterEvent> events(_i2.FilterOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #events,
          [options],
        ),
        returnValue: _i5.Stream<_i2.FilterEvent>.empty(),
      ) as _i5.Stream<_i2.FilterEvent>);
  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i4.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_10(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_10(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_10(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_10(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_10(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_10(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<_i6.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i5.Future<_i6.Uint8List>);
  @override
  _i5.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i5.Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_11(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i5.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
